//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleModel
    {
        public int Id { get; set; }
        public int MakeId { get; set; }
        public string ModelName { get; set; }
        public string ModelAbbreviation { get; set; }
    
        public virtual VehicleMake VehicleMake { get; set; }
    }
}
